# Generated by Django 3.2 on 2021-12-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('idsub_category', models.AutoField(primary_key=True, serialize=False)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=155, null=True)),
                ('current_price', models.FloatField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=245, null=True)),
                ('image', models.CharField(blank=True, max_length=245, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'sub_category',
                'managed': True,
            },
        ),
    ]
